name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (patch, minor, major, or specific version)"
        required: true
        default: "patch"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Bump version, commit & tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi

          VERSION="${VERSION#v}"

          echo "Bumping version to $VERSION..."
          npm version "$VERSION" --no-git-tag-version

          git add package.json package-lock.json
          git commit -m "chore: bump version to $VERSION"
          git tag "v$VERSION"

          echo "Pushing commit & tag..."
          git push origin HEAD
          git push origin "v$VERSION"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_INITIAL }}
        run: |
          echo "🚀 Publishing to npm..."
          npm publish --access public
